# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d1e4b4b86f5afd3f5e7e9b8c0c90bf71d56017a522c84c71788625a6e47ae90b416b36de5675a7432d8983d37f7dc139bcc7e2105098078af2fbb12bfdcbe9c

test:
  secret_key_base: 9be006101d5d9e9a6167b1bde5c3c66d2c8e9e6251524eab89f54998384c2a1234fd3ddfa32da33568a5636d2c263f29f6b7d95833dd1c4d705c6b6b199b7c56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
